version: '3'

services:
  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/code
      - .db_data/db.sqlite3:/db.sqlite3
    env_file:
      - ./.env
    ports:
      - "8000:8000"