# Generated by Django 3.0.3 on 2021-10-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
